
migrations:
  stage: build
  script:
    - python3 manage.py makemigrations
    # - python3 manage.py makemigrations myapp
    - python3 manage.py migrate
    - python3 manage.py check

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
